### ISSUE TITLE
Critical: Followin code should be in controller

### ISSUE THREAD

**Issue by ArthurAlexandersson** [jmarkusson/TDA553-lab1#27]
This code should be in one or more of the Controllers, because it is about taking input from the user, not telling the user the state of the model. (Hint; It will be easiest if you make all the code relating to the buttons and spinner into Controllers.)
https://github.com/jmarkusson/TDA553-lab1/blob/76148f7dfc609db419311ad311f2e5bd6726262f/VehicleView.java#L112-L179

**Comment by ValleBisander** [comment]
Fixed
