### ISSUE TITLE
Non-Critical: DIP, and Encapsulation

### ISSUE THREAD

**Issue by ArthurAlexandersson** [jmarkusson/TDA553-lab1#28]
Would be better to use a higher abstraction for ArrayList<>, i.e. List<Vehicle>. The list should also be made private, along with all other instance variables. 
https://github.com/jmarkusson/TDA553-lab1/blob/76148f7dfc609db419311ad311f2e5bd6726262f/VehicleModel.java#L8

**Comment by ValleBisander** [comment]
Fixed
