### ISSUE TITLE
Non-Critical: Avoid instanceof

### ISSUE THREAD

**Issue by ArthurAlexandersson** [jmarkusson/TDA553-lab1#29]
OCP: Avoid instanceof. A better way to write the code would be to have one list of vehicles, one list of vehicles with turbo, onelist of vehicles with platform. Alternatively, split this class into three (or more) Controllers.
https://github.com/jmarkusson/TDA553-lab1/blob/76148f7dfc609db419311ad311f2e5bd6726262f/VehicleModel.java#L68-L102

**Comment by ValleBisander** [comment]
Fixed
